FROM php:8.1.12-fpm

COPY php.ini /usr/local/etc/php/

RUN apt update \
    && apt install -y default-mysql-client zlib1g-dev libzip-dev unzip nodejs npm \
    && docker-php-ext-install pdo_mysql zip

RUN npm install -g n && n 14.21.3

RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && composer self-update

WORKDIR /var/www